# Generated by Django 6.1 on 2026-08-16 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medical_conditions', models.TextField(blank=True)),
                ('smoke', models.CharField(max_length=20)),
                ('drink_alcohol', models.CharField(max_length=20)),
                ('diet', models.CharField(max_length=50)),
                ('exercise', models.CharField(max_length=50)),
                ('allergies', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediai.consultation')),
            ],
        ),
    ]
