# Generated by Django 6.1 on 2026-08-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediai', '0003_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
